# Generated by Django 6.0 on 2026-03-31 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_batch_code_product_planting_area_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='quantity_kg',
        ),
    ]
